// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ko'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 오​늘​의​ ​가​격
	 */
	TITLE_PRICE: string
	/**
	 * 가​격​ ​추​이
	 */
	TITLE_TREND: string
	/**
	 * 지​역​별​ ​가​격
	 */
	TITLE_REGIONALMARKETPRICE: string
	/**
	 * 최​저​가
	 */
	PRICE_LOW: string
	/**
	 * 평​균​가
	 */
	PRICE_AVERAGE: string
	/**
	 * 최​고​가
	 */
	PRICE_HIGH: string
	/**
	 * 분​류
	 */
	MARKETTYPE: string
	/**
	 * 업​데​이​트​ ​시​간
	 */
	UPDATETIME: string
	/**
	 * 로​딩​ ​중​.​.​.
	 */
	LOADING: string
	MAP_MARKET: {
		/**
		 * 전​통​시​장
		 */
		'00': string
		/**
		 * 대​형​유​통
		 */
		'01': string
	}
	MAP_REGION: {
		/**
		 * 서​울
		 */
		'0000': string
		/**
		 * 부​산
		 */
		'0001': string
		/**
		 * 대​구
		 */
		'0002': string
		/**
		 * 인​천
		 */
		'0003': string
		/**
		 * 광​주
		 */
		'0004': string
		/**
		 * 대​전
		 */
		'0005': string
		/**
		 * 울​산
		 */
		'0006': string
		/**
		 * 세​종
		 */
		'0007': string
		/**
		 * 수​원
		 */
		'0008': string
		/**
		 * 성​남
		 */
		'0009': string
		/**
		 * 고​양
		 */
		'0010': string
		/**
		 * 용​인
		 */
		'0011': string
		/**
		 * 춘​천
		 */
		'0012': string
		/**
		 * 강​릉
		 */
		'0013': string
		/**
		 * 청​주
		 */
		'0014': string
		/**
		 * 천​안
		 */
		'0015': string
		/**
		 * 전​주
		 */
		'0016': string
		/**
		 * 순​천
		 */
		'0017': string
		/**
		 * 포​항
		 */
		'0018': string
		/**
		 * 안​동
		 */
		'0019': string
		/**
		 * 창​원
		 */
		'0020': string
		/**
		 * 김​해
		 */
		'0021': string
		/**
		 * 제​주
		 */
		'0022': string
	}
}

export type TranslationFunctions = {
	/**
	 * 오늘의 가격
	 */
	TITLE_PRICE: () => LocalizedString
	/**
	 * 가격 추이
	 */
	TITLE_TREND: () => LocalizedString
	/**
	 * 지역별 가격
	 */
	TITLE_REGIONALMARKETPRICE: () => LocalizedString
	/**
	 * 최저가
	 */
	PRICE_LOW: () => LocalizedString
	/**
	 * 평균가
	 */
	PRICE_AVERAGE: () => LocalizedString
	/**
	 * 최고가
	 */
	PRICE_HIGH: () => LocalizedString
	/**
	 * 분류
	 */
	MARKETTYPE: () => LocalizedString
	/**
	 * 업데이트 시간
	 */
	UPDATETIME: () => LocalizedString
	/**
	 * 로딩 중...
	 */
	LOADING: () => LocalizedString
	MAP_MARKET: {
		/**
		 * 전통시장
		 */
		'00': () => LocalizedString
		/**
		 * 대형유통
		 */
		'01': () => LocalizedString
	}
	MAP_REGION: {
		/**
		 * 서울
		 */
		'0000': () => LocalizedString
		/**
		 * 부산
		 */
		'0001': () => LocalizedString
		/**
		 * 대구
		 */
		'0002': () => LocalizedString
		/**
		 * 인천
		 */
		'0003': () => LocalizedString
		/**
		 * 광주
		 */
		'0004': () => LocalizedString
		/**
		 * 대전
		 */
		'0005': () => LocalizedString
		/**
		 * 울산
		 */
		'0006': () => LocalizedString
		/**
		 * 세종
		 */
		'0007': () => LocalizedString
		/**
		 * 수원
		 */
		'0008': () => LocalizedString
		/**
		 * 성남
		 */
		'0009': () => LocalizedString
		/**
		 * 고양
		 */
		'0010': () => LocalizedString
		/**
		 * 용인
		 */
		'0011': () => LocalizedString
		/**
		 * 춘천
		 */
		'0012': () => LocalizedString
		/**
		 * 강릉
		 */
		'0013': () => LocalizedString
		/**
		 * 청주
		 */
		'0014': () => LocalizedString
		/**
		 * 천안
		 */
		'0015': () => LocalizedString
		/**
		 * 전주
		 */
		'0016': () => LocalizedString
		/**
		 * 순천
		 */
		'0017': () => LocalizedString
		/**
		 * 포항
		 */
		'0018': () => LocalizedString
		/**
		 * 안동
		 */
		'0019': () => LocalizedString
		/**
		 * 창원
		 */
		'0020': () => LocalizedString
		/**
		 * 김해
		 */
		'0021': () => LocalizedString
		/**
		 * 제주
		 */
		'0022': () => LocalizedString
	}
}

export type Formatters = {}
