// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ko'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 테​스​트​ ​섹​션​ ​1
	 */
	TITLE_PRICE: string
	/**
	 * 테​스​트​ ​섹​션​ ​2
	 */
	TITLE_TREND: string
	/**
	 * 테​스​트​ ​섹​션​ ​3
	 */
	TITLE_REGIONALMARKETPRICE: string
	/**
	 * 최​저​가
	 */
	PRICE_LOW: string
	/**
	 * 평​균​가
	 */
	PRICE_AVERAGE: string
	/**
	 * 최​고​가
	 */
	PRICE_HIGH: string
	/**
	 * 분​류
	 */
	MARKETTYPE: string
	/**
	 * 업​데​이​트​ ​시​간
	 */
	UPDATETIME: string
	/**
	 * 로​딩​ ​중​.​.​.
	 */
	LOADING: string
	MAP_MARKET: {
		/**
		 * 전​통​시​장
		 */
		'00': string
		/**
		 * 대​형​유​통
		 */
		'01': string
	}
	MAP_REGION: {
		/**
		 * 서​울
		 */
		'0000': string
		/**
		 * 부​산
		 */
		'0001': string
		/**
		 * 대​구
		 */
		'0002': string
	}
}

export type TranslationFunctions = {
	/**
	 * 테스트 섹션 1
	 */
	TITLE_PRICE: () => LocalizedString
	/**
	 * 테스트 섹션 2
	 */
	TITLE_TREND: () => LocalizedString
	/**
	 * 테스트 섹션 3
	 */
	TITLE_REGIONALMARKETPRICE: () => LocalizedString
	/**
	 * 최저가
	 */
	PRICE_LOW: () => LocalizedString
	/**
	 * 평균가
	 */
	PRICE_AVERAGE: () => LocalizedString
	/**
	 * 최고가
	 */
	PRICE_HIGH: () => LocalizedString
	/**
	 * 분류
	 */
	MARKETTYPE: () => LocalizedString
	/**
	 * 업데이트 시간
	 */
	UPDATETIME: () => LocalizedString
	/**
	 * 로딩 중...
	 */
	LOADING: () => LocalizedString
	MAP_MARKET: {
		/**
		 * 전통시장
		 */
		'00': () => LocalizedString
		/**
		 * 대형유통
		 */
		'01': () => LocalizedString
	}
	MAP_REGION: {
		/**
		 * 서울
		 */
		'0000': () => LocalizedString
		/**
		 * 부산
		 */
		'0001': () => LocalizedString
		/**
		 * 대구
		 */
		'0002': () => LocalizedString
	}
}

export type Formatters = {}
